name: Crystal CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: shards install
      uses: docker://hub.docker.com/r/crystallang/crystal/tags
    - name: Run tests
      run: crystal spec
      uses: docker://hub.docker.com/r/crystallang/crystal/tags
